language: java
jdk:
  # Ceylon 1.3.3 is not ready for java 10 or 11:
  #     ceylon compile: invalid source release: 10
  #     ceylon compile: invalid source release: 11
  # Ceylon 1.3.3 is not ready for java 9:
  #     ceylon format: Could not load module 'ceylon.formatter/1.3.3' because: com.
  #     redhat.ceylon.cmr.ceylon.loader.ModuleNotFoundException: Could not find module:
  #     javax.xml/7
  # Try later version of Java when using a later version of Ceylon.
  # Arbitrarily selected openjdk8 over oraclejdk8, they both work fine.
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
install:
  - bin/fetch-configlet
  - curl -s https://get.sdkman.io | bash
  - source $HOME/.sdkman/bin/sdkman-init.sh
  - sdk install ceylon
script:
  - bin/configlet lint .
  - bin/compile-all-stubs
  - bin/test-all-exercises
  - |
    if ! ceylon format exercises; then
      echo "'ceylon format' couldn't run!"
      exit 1
    fi
    if ! git diff --exit-code; then
      echo "'ceylon format' found differences! Please match 'ceylon format' so this repo can have consistent style!"
      exit 1
    fi
